### ISSUE TITLE
Ability to access/output GRIB message as raw bytes

### ISSUE THREAD

**Issue by jasonwashburn** [eengl/grib2io#4]
It would be beneficial to add a method to return the GRIB2 message as raw bytes. Something akin to `Grib2Message.to_bytes()` or similar. It should be an easy addition as I am currently achieving the same functionality by accessing the `._msg` attribute of Grib2Message directly. Adding a method to get the data would be a cleaner implementation than calling a protected attribute. This is useful for writing the GRIB formatted data to other mediums, for instance, directly to S3 from memory without the need to create temporary files.

If you're open to contributions I'm willing to submit a PR.

**Comment by eengl** [comment]
Hi @jasonwashburn.  Great idea!  Feel free to submit PR.

**Comment by jasonwashburn** [comment]
Great, will do! Just out of curiosity, have you given any thought to what license you're planning to use?

**Comment by eengl** [comment]
Totally forgot about the license.  I am planning to go with MIT.

**Comment by jasonwashburn** [comment]
got side tracked by some other stuff going on, but going to knock this out.

On a related note...what type of system are you using for development? The jasper libraries have proven to be a pain on more recent OS's. I've been using a docker container running an older version of debian since thats basically how I used it before...but was curious if you had it running on some more modern, or were just using a VM or something similar?
