### ISSUE TITLE
Grib file behavior not following documentation

### ISSUE THREAD

**Issue by Marston** [eengl/grib2io#6]
I'm trying to learn the grib2io API version 0.8.0 on a CentOS7 WSL2, and I'm running into some issues.
I can open this grib file from NCEP no problem, but when I open the file with grib2io:

     `grbh = grb2.open(grbPath, mode='r')`
Which gives me something I can loop over to get the list of attributes and names in each message, but I keep getting each message as a list and I cannot access the data. 
I can access some header information via the grbh methods: name, mode, variables (shortNames), size, messages (total) etc.
But like I said, then I access one of these records, I keep getting a list and no way to access the data. 
Not sure if I have to count each of these roughly 74 list members to get the value. 

The documentation is not helping me and I cannot find a good example. Is grib2io functioning as it should? If so, how do I get to the data?

**Comment by eengl** [comment]
Hi!  So in your example usage, `grbh` will be an instance of `grib2io.open`, which you can iterate on.  When you iterate on grib2io.open objects, the iterator returns Grib2Message objects as it sequentially reads the file.

```python
g2 = grib2io.open(path)
for msg in g2:
    ....
```

When you select the GRIB2 messages by a number or range/slice, a list of Grib2Message objects will be returned, even if it is 1 message.  For example

```python
msg = g2[50][0] # Selecting the 50th record requires me to provide an additional index
```

Admittedly, it is a bit cumbersome but my intention was to always return the same type of object (i.e. a list).  Of course, this could always change before v1.0.

Please let me know if this is the behavior you are seeing.

**Comment by Marston** [comment]
Hi,

Thank you for your response. I had to restart my VS Code and now I don't get a list in all cases. The behaviour you are seeing.
One request, however, is to have dictionaries rather than lists which would be easier to look at the keys and value pairs, rather than with lists.

**Comment by Marston** [comment]
Question: can you explain the behaviour: `grbh[50]` is a list of length 1.  Then what is being selected with `x = grbh[50][0]`?
I know the return for the second is a `grib2io._grib2io.Grib2Message`. I'm not understanding the mechanism in the code. Is the second `[0]` selecting the raster `band`?

**Comment by Marston** [comment]
Question: do you have a sample script of how to write a message? Perhaps even a template?

**Comment by Marston** [comment]
Hi,

I am wondering how to write a `grib2` file with this API. 
If I parse and old CF compliant grib file and save the attributes in a dictionary, how do I add these attributes, the geolocation, and data, in addition to writing to a file name?

This is how far I have gotten: `g2file = grib2io.Grib2Message()`
I can add attributes in this manner:  `g2file.attr = xxxx`
But how do I add `lat` and `lon` arrays and the `2D data array`?
Also how do I write out the grib file?

If you could give me some examples of these I would be truly grateful.

**Comment by jasonwashburn** [comment]
Marston, I didn't make the connection until this morning :)

If you'd like we can get together and walk through how we used it in a little more detail and take a look at what you've got. I'll send you an email.

Jason

**Comment by Marston** [comment]
Yes, let's get together and complete this issue.

**Comment by eengl** [comment]
Marston,

Apologies for the lack of response.  It is a crazy time of the year preparing for the holidays.

Let me address how to create an instance of `grib2io.Grib2Message` from scratch.  To do this, call the class constructor with ONLY the `discipline` and `idsect` keywords as shown below:

```python
msg = grib2io.Grib2Message(discipline=<int>,idsect=<list>)
```

See https://eengl.github.io/grib2io/grib2io.html#Grib2Message.__init__ which describes what to provide in these keywords.  `msg` is now a Grib2Message with proper information for GRIB2 sections 0 and 1.

To fill in the remaining GRIB2 sections (3,4,5,6,7,8), perform the following:

```python
msg.addgrid(...) # Add Section 3 information
msg.addfield(...) # Add Section 4, 5, 6, 7 information.  Note that field argument is the data.
msg.end() # Add Section 8 (End Section).  This terminates the GRIB2 message in it binary encoded form.
```

The documentation provides more information as to what to provide to each of these method calls.

This process of creating a Grib2Message from scratch is same as the predecessor to grib2io, ncepgrib2, which used to be a part of the pygrib package.

**Comment by Marston** [comment]
Thank you for your help and example. I can create now a grib2 file for a 2D array but I don't know how to a 3D array where time is the 3rd dim or s 4D array if lev is now another dimension. How do I add higher dimensions?

**Comment by eengl** [comment]
For 3- or 4-D data, you need to iterate over those dimension indices and create a GRIB2 message for each x(i) by y(j) 2D grid within the 3D or 4D data array.

**Comment by Marston** [comment]
I'm not sure I follow your train of thought. How would I identify each 2D field?
One last thing, how do I get grib2io to recognize a locally defined grib table?

**Comment by eengl** [comment]
For example, you have a 3D array of 2m temperature sized (10,500,1000) where 10 is the number of "times"; 500 is the y (or j-coordinate); and 1000 is the x (or x-coordinate).  In other words, you have 10 horizontal temperature grids at different times.

```python
import grib2io
import numpy as np

nx, ny, nt = 1000, 500, 10
tempdata = np.ones((nt,ny,nx),dtype=np.float32) # Assume these are real temperature data
g2file = grib2io.open("temp_test.grib2",mode="w") # Create a new GRIB2 file for writing

# Iterate over the time dimension index of the 0-th index
for n in range(template.shape[0]):
    tmp = tempdata[n,:,:] # This is 2D temp grid
    msg = grib2io.Grib2Message(discipline=<int>,idsect=<list>)
    msg.addgrid(...) # Add Section 3 information
    msg.addfield(...) # Add Section 4, 5, 6, 7 information.  Note that field argument is where you pass tmp array.
    msg.end() # Add Section 8 (End Section).  This terminates the GRIB2 message in it binary encoded form.
    g2file.write(msg)
g2file.close()
```

Regarding a locally defined GRIB2 table...there is no explicit mechanism right now to handle local tables.

**Comment by Marston** [comment]
Thank you very much. 
Are there any plans to be able to use section 2 (local use) for grib2io?

**Comment by eengl** [comment]
Closing this issue.  Local use section request is now a new issue #9
