### ISSUE TITLE
Consider adding Gitpod configuration to simplify development environment for contributors.

### ISSUE THREAD

**Issue by jasonwashburn** [eengl/grib2io#7]
I've created a Gitpod configuration and custom image build which has greatly simplified my development workflow for contributing to grib2io. Once you've created a free account (up to 50 hours per month) at [gitpod.io](https://gitpod.io), you can open any GitHub repository in a throwaway development environment simply by prepending the repository url with `https://gitpod.io/#`. For example, to test my configuration you can go to [https://gitpod.io/#https://github.com/jasonwashburn/grib2io/tree/add-gitpod-config](https://gitpod.io/#https://github.com/jasonwashburn/grib2io/tree/add-gitpod-config).

You can also install their browser extension which adds a "Gitpod" button whenever you're viewing a GitHub repo. Clicking on it opens that repo up in a new workspace automatically, and you're ready to make changes, test and execute code.
![image](https://user-images.githubusercontent.com/35488541/149644371-b1b1dcc3-dcd8-4d11-ba01-d320d7801ac1.png)

There is sometimes a small delay the first time you load the environment while it builds a container image, but once you've added your repo as a project on Gitpod, it will attempt to pre-build a new image any time you make changes that affect the container image. When an image is already built, environments open within 5-10 seconds inside your browser in a web version of Visual Studio Code (which is surprisingly comparable to the desktop IDE). Alternatively, it will present you with the option to open it inside Visual Studio Code on your desktop as well.

One of the other great benefits is the ability to launch new instances from any branch, and even test PRs without having to pull or checkout anything.

Take a look, and if you're interested in adding it to the project I'll submit a PR.

**Comment by eengl** [comment]
Great idea!  And thank you for passing along this information about Gitpod.io.  I did not know of it existence.  PR welcomed!

**Comment by jasonwashburn** [comment]
Submitted PR #8. Looking forward to using it for future contributions!
