### ISSUE TITLE
Ability to add local use section to new Grib2Messages

### ISSUE THREAD

**Issue by eengl** [eengl/grib2io#9]
Add method that allows you to add a Local Use Section (section 2) to a new Grib2Message.

**Comment by eengl** [comment]
Support has been added with commit https://github.com/eengl/grib2io/commit/0f8625805257ab9880c26ca1307da3bd425b8e29

**Comment by Marston** [comment]
Could you please give an example of how to use this feature? How would the local table look like and how to get it into grib2io?
Nice feature that I would begin implementing soon.

**Comment by eengl** [comment]
Sure...it is fairly straightforward process.  Here is the **updated** example from the other issue thread

```python
import grib2io
import numpy as np

nx, ny, nt = 1000, 500, 10
tempdata = np.ones((nt,ny,nx),dtype=np.float32) # Assume these are real temperature data
g2file = grib2io.open("temp_test.grib2",mode="w") # Create a new GRIB2 file for writing

# Iterate over the time dimension index of the 0-th index
for n in range(template.shape[0]):
    tmp = tempdata[n,:,:] # This is 2D temp grid
    msg = grib2io.Grib2Message(discipline=<int>,idsect=<list>)
    msg.addlocal(...) # Add Section 2 (Local Use Section)
    msg.addgrid(...) # Add Section 3 information
    msg.addfield(...) # Add Section 4, 5, 6, 7 information.  Note that field argument is where you pass tmp array.
    msg.end() # Add Section 8 (End Section).  This terminates the GRIB2 message in it binary encoded form.
    g2file.write(msg)
g2file.close()
```

All you have to do is call the `addlocal()` method after you initialize the new `Grib2Message` object.  The method accepts 1 argument and that arg must be of type `bytes` and is the local use section data.  The Local Use Section can literally be **_anything_** you want to encode into that section.  Just make sure you pass along instructions to end users on how to decode the section.
